---
title: "Unmixing SigColon"
author: "Yuchen Li"
date: "2026-07-29"
output: 
  html_document:
    code_folding: "hide"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(flowCore)
library(flowSpectrum)
library(ggcyto)
library(matrixStats)
library(data.table)
set.seed(233)
dir.create("./rds")
dir.create("./plots")
```


### Load pre-gated fcs files for cell only reference controls 

```{r, message=FALSE, warning=FALSE}
file.dir <-"./ref controls"
files <- dir(file.dir, pattern = "fcs$", full.names=T)
as.matrix(files)

# read in fcs files
dat <- lapply(files, read.FCS)
names(dat) <-gsub("./ref controls/","",files)
as.matrix(names(dat))
```

## Generate the data frame of reference control spectral profiles

```{r, message=FALSE, warning=FALSE, echo=FALSE}
p1 <- lapply(seq(2,length(dat), by = 2), function(i){spectralplot(dat[[i]], normalize = TRUE, guessPop = TRUE, unstained = dat[[i-1]])$data})

#Name the list of new dfs
 names(p1) <- gsub("./ref control/", "",names(dat[seq(2,length(dat),2)]))
 names(p1) <- gsub("_pos.fcs", "",names(dat[seq(2,length(dat),2)]))
 print(as.matrix(names(p1)))
 
 
# Reorder the channels if you processed controls in flowjo
 
aurora_channels <- c('UV1-A',  'UV2-A',  'UV3-A',  'UV4-A',  'UV5-A',  'UV6-A',  'UV7-A',  'UV8-A',  'UV9-A',  'UV10-A','UV11-A', 'UV12-A', 'UV13-A', 'UV14-A', 'UV15-A', 'UV16-A', 'V1-A',   'V2-A',  
'V3-A',   'V4-A',   'V5-A',   'V6-A',   'V7-A',   'V8-A',   'V9-A',   'V10-A',  'V11-A',  'V12-A',  'V13-A',  'V14-A',  'V15-A',  'V16-A',  'B1-A',   'B2-A',   'B3-A',   'B4-A',  'B5-A',   'B6-A',   'B7-A',   'B8-A',   'B9-A',   'B10-A',  'B11-A',  'B12-A',  'B13-A',  'B14-A',  'YG1-A',  'YG2-A',  'YG3-A',  'YG4-A',  'YG5-A',  'YG6-A',  'YG7-A',  'YG8-A', 'YG9-A',  'YG10-A', 'R1-A',   'R2-A',   'R3-A',   'R4-A',   'R5-A',   'R6-A',   'R7-A',   'R8-A'  )


for (i in 1:length(p1)){
  p1[[i]] <- p1[[i]][match(aurora_channels, p1[[i]]$`rownames(df)`),]
}
 
# add a sample column for plotting
  for(i in 1:length(p1)){p1[[i]]$sample = names(p1)[i]}
 
cvars<-gsub("\ ","",apply(expand.grid(c("UV", 'V', 'B', "YG", "R"),1:16,"-A") %>% 
                            mutate(Var1=factor(Var1,levels=unique(Var1))) %>% 
                            arrange(Var1,Var2),1,function(X) paste0(X,collapse="")))

# combine the df into a big df
df <- df <- dplyr::bind_rows(c(p1))

## Import AF profile
dir <- "./af"
files <- dir(dir, pattern = "fcs$", full.names=T)
as.matrix(files)

# read in fcs files
dat <- lapply(files, read.FCS)

# Extract normalised spectra
af <- lapply(1:length(dat), function(i){spectralplot(dat[[i]], normalize = TRUE)$data})
names(af) <- names(dat)

# Reorder the channels
af <- af[[1]]
af<- af[match(aurora_channels, af$`rownames(df)`),]
af$sample <- "AF"

# attaching AF profile to the spectral profile data frame and list
df <- rbind(df,af)
p1$AF <- af
```

# Generate spectral profiles including AF

```{r}
markers <- unique(df$sample)

# Visualise the spectral profiles
df %>% 
  mutate(Detector=factor(`rownames(df)`,levels=cvars[cvars %in% `rownames(df)`])) %>% 
    ggplot(aes(Detector,medians.max.medians.,group=sample,color=sample)) + 
      geom_line(linewidth = 0.7) + geom_point() + 
       guides(x=guide_axis(angle=45)) + theme_bw(base_size=8) + 
        theme(legend.text=element_text(size=5)) + 
        theme(legend.position = "right")+
        theme(legend.title = element_text(size=0.1))+
        ylab("")+
        xlab("")

#save the plot
ggsave("./plots/ref control spectral profiles.png", width = 40, height = 10, units = c("cm"))

```


## Unmixing using OLS via SVD

### Generate the spectral profile matrix and spectral unmixing matrix using SVD

```{r, fig.height=6, fig.width=15}

# construct the spectra matrix
Mlist <- list()

for (i in 1:length(table(df$sample))){
    Mlist[[i]] <- as.matrix(p1[[i]]$medians.max.medians.)
}

spectra_matrix <- do.call(cbind, Mlist)
rm(Mlist)

colnames(spectra_matrix) <- names(p1)

# construct the unmixing matrix

sample_name <- "Colon LP"

# SVD for M
svd_M <- svd(spectra_matrix)
pseudo_inver_M <- (svd_M$v) %*% diag(svd_M$d^(-1)) %*% t(svd_M$u)

rownames(pseudo_inver_M) <- colnames(spectra_matrix)
colnames(pseudo_inver_M) <-cvars[cvars %in% df$`rownames(df)`]

# heatmap visualisation of the unmixing matrix
pheatmap(pseudo_inver_M, 
         main = "Unmixing matrix by OLS",
         color = colorRampPalette(c("blue", "white", "red"))(100),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         angle_col = c("45"),
         filename = paste0("./plots/OLS_unmixing_matrix", sample_name, ".png"),
       #  cellwidth = 5.5,
        width = 12,
        height = 4)

```


### Load in raw sample data and unmix

```{r}
fs_path <- "./CUM_Full-stain_2025_08_22_14_43_42.fcs"
sample <- read.FCS(fs_path, transformation = "linearize-with-PnG-scaling")
```

```{r}
# take only the fluorescence channels to go into the unmixing
sample_fluo<-exprs(sample[,sample@parameters@data$name[sample@parameters@data$name %in% df$`rownames(df)`]])
dim(sample_fluo)

colnames(sample_fluo) <- NULL

# transpose it into the cells as columns vs channels as rows format
sample_fluo<- as.data.table(sample_fluo)
sample_fluo<- transpose(sample_fluo)
sample_fluo <- as.matrix(sample_fluo)

# Applying unmixing matrix
unmixed_matrix <- pseudo_inver_M %*% sample_fluo

# Transpose to make the cells on rows again to match the original data
t_unmixed_matrix <- t(unmixed_matrix)
rm(unmixed_matrix, sample_fluo)

colnames(t_unmixed_matrix) <- gsub("_","_unmixed_", colnames(t_unmixed_matrix))

#Add these columns to the Time and FSC, SSC channels
unmixed_data <- cbind(exprs(sample[,sample@parameters@data$name[!sample@parameters@data$name %in% df$`rownames(df)`]]),
      t_unmixed_matrix)
rm(p1,dat)
```

### Write out the data

```{r}
# write the fcs file
sample_name <- "Colon_LP"
ff <- flowFrame(as.matrix(unmixed_data))
write.FCS(ff, filename = paste0("ols_unmixed_", sample_name, ".fcs"))
# Save the unmixing results
saveRDS(unmixed_data,paste0("./rds/OLS_unmixed_wAF_",sample_name, ".rds"))

```

### Calculate var x (M^T M)^(-1)

```{r, fig.height=7, fig.width=8}
M <- spectra_matrix

# Calculate M^T
M <- as.data.table(M)
M_t <- transpose(M)
M <- as.matrix(M)
M_t <- as.matrix(M_t)
rownames(M_t) <- colnames(M)

# (M^T M)^(-1) (Kmet, 2025, the endmember-dependent component of the spectra)
mtm <- solve(M_t %*% M)
#saveRDS(mtm, "./rds/20260705_VE_fluorophore_mtm-1.rds")

# plotting
mtm[upper.tri(mtm)] <- NA

mtm %>% 
  reshape2::melt() %>% 
ggplot(aes(x = Var2, y = Var1, fill = value)) +
  geom_tile(color = "white", linewidth = 0.5) + 
  scale_fill_gradient2(
    low = "white",
    mid = "grey",
    high = "red",
    midpoint = 0,
    limits = c(0, 5),
    na.value = "transparent",
    oob = scales::squish    
  ) +
  coord_fixed() + # square tiles
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    panel.grid = element_blank()
  ) +
  labs(fill = "Value", x = NULL, y = NULL)

```
